#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse

# Import from Awesome_package
import Awesome_package
from Awesome_package.lib import try_me

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'Awesome_package_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    folder_source, _ = split(Awesome_package.__file__)
    try_me()
